version: '3.9'

services:
  react-app:
    build:
      context: .
      dockerfile: reactApp/Dockerfile
    volumes:
      - ./reactApp:/opt/gim-dashboard/reactApp/
    ports:
      - "3001:3001"
    stdin_open: true
    restart: always

 #nginx:
 #  image: nginx:latest
 #  container_name: nginx-reactApp
 #  restart: always
 #  ports:
 #    - "81:81"
 #    - "3002:3002"
 #  volumes:
 #    - /opt/gim-dashboard/nginx.conf:/etc/nginx/nginx.conf:ro
 #    - /opt/gim-dashboard/reactApp/cert.pem:/etc/nginx/certs/cert.pem
 #    - /opt/gim-dashboard/reactApp/key.pem:/etc/nginx/certs/key.pem
 #  depends_on:
 #    - react-app
 #  command: [ "nginx", "-g", "daemon off;" ]
