version: '3.9'
services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./reactApp:/opt/gim-dashboard/reactApp # ローカルをコンテナ内にマウント
    command: sh -c "yarn start"
    ports:
      - "3001:3001"
    stdin_open: true
    restart: always
